// Plain-dictionary entries for the supply-chain and WMS vocabulary a swi-tch
// recruiter needs to be conversant in. No opinions; just definitions.

export type GlossaryTerm = {
  term: string
  expansion?: string
  category: 'process' | 'tech' | 'role' | 'metric' | 'standard'
  short: string
  long?: string
  related?: string[]
}

export const GLOSSARY: GlossaryTerm[] = [
  // ─── Process ───────────────────────────────────────────
  {
    term: 'Wave picking',
    category: 'process',
    short: 'Releasing groups of orders together in a "wave" so the warehouse picks them as a coordinated batch.',
    long: 'A wave is a planned release of orders, scheduled by the WMS based on factors like carrier cut-off, shipment lane, customer priority or labour availability. Wave picking lets a site smooth labour, sequence work logically and consolidate at pack-out. It is most common in retail and 3PL operations with strong daily peaks.',
    related: ['Batch picking', 'Allocation', 'Cluster picking'],
  },
  {
    term: 'Batch picking',
    category: 'process',
    short: 'Picking the same SKU for several orders at once, then sorting into individual orders downstream.',
    long: 'Pickers travel the warehouse less by collecting one large quantity of a SKU that satisfies many orders, then a downstream sortation step (manual, conveyor or put-wall) splits the picked quantity into customer orders.',
    related: ['Wave picking', 'Cluster picking', 'Put-to-light'],
  },
  {
    term: 'Cluster picking',
    category: 'process',
    short: 'A single picker fulfils several orders simultaneously by carrying a multi-tote cart and picking each SKU into the correct tote.',
    long: 'Cluster picking is common in e-commerce. The picker walks the route once with a cart that holds 8–24 totes; the WMS or a put-light tells the picker which tote each unit belongs to.',
    related: ['Batch picking', 'Pick-to-light'],
  },
  {
    term: 'Zone picking',
    category: 'process',
    short: 'The warehouse is split into zones; each picker stays in their zone and orders flow between zones.',
    long: 'Orders either pass between zones in sequence ("pick and pass") or are picked in parallel and consolidated downstream. Zone picking limits picker travel and is often used in larger DCs alongside conveyors.',
    related: ['Wave picking', 'Batch picking'],
  },
  {
    term: 'Pick-to-light',
    category: 'process',
    short: 'Light modules at storage locations indicate quantity to pick; the operator confirms by pressing the module.',
    long: 'Pick-to-light is fast and accurate but expensive to install at scale; it is most commonly used in dense, fast-moving pick faces such as pharmacy and small-parts pharma.',
    related: ['Put-to-light', 'Voice picking'],
  },
  {
    term: 'Put-to-light',
    category: 'process',
    short: 'Light modules at put-walls indicate which compartment each picked unit belongs to during sortation.',
    long: 'Put-to-light is heavily used at the consolidation step after batch or cluster picking, especially in e-commerce where many small orders need to be split out of a bulk pick.',
    related: ['Pick-to-light', 'Batch picking'],
  },
  {
    term: 'Voice picking',
    category: 'process',
    short: 'Operators wear a headset; the WMS calls out tasks and the operator confirms by speaking back.',
    long: 'Voice-directed work keeps operators hands-free and eyes-up. It is widely used in grocery, cold-store and case-pick environments. Honeywell Vocollect is the dominant historical voice platform; Körber Cohesio, Lucas Systems and several WMS-native voice modules also operate in this space.',
    related: ['RF gun', 'WMS'],
  },
  {
    term: 'Cross-docking',
    category: 'process',
    short: 'Inbound goods are routed directly to outbound shipments without going into long-term storage.',
    long: 'Cross-docking minimises handling and inventory holding. It is most common where inbound and outbound lanes are tightly coordinated — store replenishment from a regional DC, retail apparel hubs, parcel cross-docks.',
    related: ['Putaway', 'Allocation'],
  },
  {
    term: 'Putaway',
    category: 'process',
    short: 'Moving received goods from the receiving dock into a storage location.',
    long: 'WMS putaway logic considers velocity, dimensions, hazmat rules, lot/serial constraints and replenishment needs. Directed putaway (the WMS picks the location) is now standard in enterprise systems.',
    related: ['Goods receipt', 'Slotting'],
  },
  {
    term: 'Replenishment',
    category: 'process',
    short: 'Moving stock from reserve / bulk locations into pick faces so picking can continue.',
    long: 'Replenishment can be triggered by min/max levels, by demand from open orders, or planned ahead of an upcoming wave. Top-off, dynamic and demand-driven are the common modes.',
    related: ['Allocation', 'Slotting'],
  },
  {
    term: 'Cycle counting',
    category: 'process',
    short: 'Counting subsets of inventory on a rolling schedule rather than a single annual stocktake.',
    long: 'Cycle counts are typically prioritised by ABC velocity or by exception (variances, negatives). The WMS schedules tasks and reconciles counts to perpetual inventory.',
    related: ['Inventory accuracy', 'Goods receipt'],
  },
  {
    term: 'Goods receipt',
    category: 'process',
    short: 'The process of accepting inbound goods into the warehouse and recording them as on-hand stock.',
    long: 'Goods receipt typically combines an ASN, a PO match, and a physical inspection, and produces an inventory adjustment that pushes stock into the WMS perpetual inventory.',
    related: ['ASN', 'Putaway', 'Goods issue'],
  },
  {
    term: 'Goods issue',
    category: 'process',
    short: 'The process of confirming that goods have left the warehouse and removing them from on-hand stock.',
    long: 'Goods issue is the inventory-movement counterpart of goods receipt. In SAP terminology this is the formal posting that ends warehouse responsibility for the stock and triggers downstream financial postings.',
    related: ['Goods receipt', 'Allocation'],
  },
  {
    term: 'Reverse logistics',
    category: 'process',
    short: 'Handling returns: receiving them back, inspecting, restocking, refurbishing, recycling or disposing.',
    long: 'Reverse logistics is a meaningful operation in apparel, electronics, e-commerce and parts distribution. WMS reverse-flow modules cover RMA receipt, disposition, grading, repackaging and reintegration into salable stock.',
    related: ['Goods receipt', '3PL'],
  },
  {
    term: 'Allocation',
    category: 'process',
    short: 'Assigning specific units of inventory to specific orders.',
    long: 'Allocation can happen at order entry, at wave release, or at pick-time. Strategies include FIFO, FEFO, lot-controlled, and serial-controlled, and pin units to specific outbound shipments.',
    related: ['Wave picking', 'Replenishment'],
  },
  {
    term: 'Drop ship',
    category: 'process',
    short: 'Goods ship directly from the supplier or vendor to the end customer, bypassing the retailer\'s warehouse.',
    long: 'Drop ship is a common pattern in e-commerce, marketplace and "endless aisle" retail. The retailer\'s WMS / OMS still needs to track the inventory commitment, but no physical handling occurs in the retailer\'s DC.',
    related: ['OMS', 'Cross-docking'],
  },
  {
    term: 'Slotting',
    category: 'process',
    short: 'Deciding where in the warehouse each SKU should live to optimise picking effort and storage density.',
    long: 'Slotting considers velocity, cube, weight, ergonomics, family / co-pick affinity, and seasonality. Most enterprise WMS products either include slotting analytics or integrate to a third-party slotting tool.',
    related: ['Replenishment', 'Putaway'],
  },

  // ─── Tech ──────────────────────────────────────────────
  {
    term: 'SKU',
    expansion: 'Stock Keeping Unit',
    category: 'tech',
    short: 'A unique identifier for a single product variant in a warehouse or store.',
    long: 'A SKU is internal to a retailer or distributor. Two retailers will use different SKUs for the same physical product. SKUs combine product, colour, size and any other attribute that differentiates how the unit is stocked.',
    related: ['UPC', 'GTIN'],
  },
  {
    term: 'UPC',
    expansion: 'Universal Product Code',
    category: 'tech',
    short: 'A 12-digit barcode standard widely used at retail point of sale, particularly in North America.',
    long: 'UPC-A is the standard 12-digit symbology. UPCs are issued under the GS1 numbering system and are a subset of the broader GTIN family.',
    related: ['EAN', 'GTIN', 'GS1'],
  },
  {
    term: 'GTIN',
    expansion: 'Global Trade Item Number',
    category: 'tech',
    short: 'GS1 identifier covering UPC, EAN, ITF-14 and other product code variants in a unified numbering scheme.',
    long: 'GTIN-12 = UPC, GTIN-13 = EAN-13, GTIN-14 = case-level identifier. GTIN is the globally consistent way to refer to a saleable product across systems and countries.',
    related: ['UPC', 'EAN', 'GS1'],
  },
  {
    term: 'EAN',
    expansion: 'European Article Number (now International Article Number)',
    category: 'tech',
    short: 'A 13-digit GS1 barcode standard widely used outside North America.',
    long: 'EAN-13 is functionally equivalent to GTIN-13 and is the standard barcode on consumer products across Europe, Asia-Pacific and Latin America.',
    related: ['UPC', 'GTIN'],
  },
  {
    term: 'ASN',
    expansion: 'Advance Shipping Notice',
    category: 'tech',
    short: 'A pre-receipt message from a supplier listing what will arrive in an inbound shipment.',
    long: 'ASNs let a warehouse plan dock and labour and pre-validate an inbound load. They typically arrive over EDI (e.g. EDI 856 in North America, DESADV in EDIFACT) or via an API. SSCC labels on cartons / pallets link the physical units back to the ASN.',
    related: ['EDI', 'SSCC', 'Goods receipt'],
  },
  {
    term: 'EDI',
    expansion: 'Electronic Data Interchange',
    category: 'tech',
    short: 'A family of structured B2B messaging standards used to exchange supply chain documents between trading partners.',
    long: 'X12 is dominant in North America (e.g. EDI 850 PO, 856 ASN, 940 warehouse shipping order); EDIFACT (ORDERS, DESADV, INVOIC) is dominant elsewhere. EDI is still the backbone of retail / manufacturing supply chains, increasingly modernised with API gateways.',
    related: ['ASN', 'OMS', 'TMS'],
  },
  {
    term: 'AS/RS',
    expansion: 'Automated Storage and Retrieval System',
    category: 'tech',
    short: 'Automated equipment that stores and retrieves loads with no operator inside the rack.',
    long: 'AS/RS includes mini-load cranes, unit-load cranes, shuttle systems and robotic cube storage (e.g. AutoStore, Exotec, Ocado, Attabotics). The WMS sees AS/RS as a destination zone; a WCS (warehouse control system) actually drives the equipment.',
    related: ['WCS', 'Conveyor', 'WES'],
  },
  {
    term: 'Conveyor',
    category: 'tech',
    short: 'Powered or gravity transport of goods between warehouse zones.',
    long: 'Conveyor systems range from simple belt sections at pack-out to multi-mile cross-belt sortation networks. The WCS controls the conveyor; the WMS provides the destination logic.',
    related: ['Sorter', 'WCS'],
  },
  {
    term: 'Sorter',
    category: 'tech',
    short: 'High-throughput equipment that diverts items to specific destinations, typically based on a barcode read.',
    long: 'Cross-belt, tilt-tray, shoe and pop-up wheel sorters are the most common types. Used heavily in parcel, e-commerce sortation and apparel DCs.',
    related: ['Conveyor', 'WCS'],
  },
  {
    term: 'RF gun',
    expansion: 'Radio-Frequency handheld scanner',
    category: 'tech',
    short: 'Mobile barcode-scanning terminal used by warehouse operators.',
    long: 'Historically Symbol / Motorola / Zebra and Honeywell are the dominant hardware vendors. WMS execution screens are designed for these devices; modern systems often run as Android or browser apps on the same hardware.',
    related: ['Voice picking', 'Barcode'],
  },
  {
    term: 'RFID',
    expansion: 'Radio-Frequency Identification',
    category: 'tech',
    short: 'Wireless tag-and-reader technology that identifies items without line-of-sight scanning.',
    long: 'RFID is heavily used in apparel (item-level tagging at brands like Inditex, Macy\'s, Decathlon), aerospace tooling, hospital asset tracking and dock-door inbound receiving. EPC Gen2 / ISO 18000-6C is the dominant air-interface standard.',
    related: ['Barcode', 'EPCIS'],
  },
  {
    term: 'Barcode',
    category: 'tech',
    short: 'Optical, machine-readable representation of data printed on labels, packaging or shelf edges.',
    long: 'Linear barcodes (UPC, EAN, Code 128, Code 39) and 2D barcodes (QR, DataMatrix, GS1 DataMatrix) are both common in warehouses. GS1-128 is the standard for logistic-unit labels.',
    related: ['UPC', 'GTIN', 'SSCC'],
  },
  {
    term: 'WMS',
    expansion: 'Warehouse Management System',
    category: 'tech',
    short: 'Software that directs and records all inventory and labour activity inside a warehouse.',
    long: 'A WMS owns receiving, putaway, storage, replenishment, allocation, picking, packing and shipping, plus labour and yard. It is the system of record for inventory inside the four walls.',
    related: ['WCS', 'WES', 'ERP'],
  },
  {
    term: 'WCS',
    expansion: 'Warehouse Control System',
    category: 'tech',
    short: 'Real-time controller for warehouse automation: conveyors, sorters, AS/RS, robotics.',
    long: 'A WCS sits between the WMS and the PLCs / robotics. It receives high-level instructions from the WMS and translates them into low-level movement commands for the equipment. Some vendors blur WMS and WCS into a single product.',
    related: ['WMS', 'WES', 'AS/RS'],
  },
  {
    term: 'WES',
    expansion: 'Warehouse Execution System',
    category: 'tech',
    short: 'A layer that orchestrates work across people, automation and processes in real time.',
    long: 'A WES typically performs functions such as wave-less order release, dynamic task allocation across operators and robots, and orchestration across multiple zones of automation. Some WMS vendors offer WES capability as part of the WMS; others provide it separately.',
    related: ['WMS', 'WCS'],
  },
  {
    term: 'MES',
    expansion: 'Manufacturing Execution System',
    category: 'tech',
    short: 'System of record for production-floor execution: shop orders, routings, machine and labour tracking.',
    long: 'In manufacturing-led supply chains the MES sits next to the WMS, with finished-goods handover and raw-material consumption being the main interface points.',
    related: ['ERP', 'WMS'],
  },
  {
    term: 'ERP',
    expansion: 'Enterprise Resource Planning',
    category: 'tech',
    short: 'Core business system covering finance, procurement, manufacturing, sales and distribution.',
    long: 'SAP S/4HANA, Oracle Fusion Cloud ERP, Microsoft Dynamics 365 Finance, Infor CloudSuite and NetSuite are major examples. The WMS is normally a downstream / adjacent system, even if part of the same vendor stack.',
    related: ['WMS', 'OMS', 'TMS'],
  },
  {
    term: 'OMS',
    expansion: 'Order Management System',
    category: 'tech',
    short: 'System that orchestrates orders across channels, sources of supply and fulfilment options.',
    long: 'In omnichannel retail the OMS decides where each order is fulfilled from (DC, store, drop-ship vendor) and hands off to the relevant WMS / store-fulfilment system. Manhattan Active Omni, Salesforce Order Management, IBM Sterling OMS and fluent commerce are examples.',
    related: ['WMS', 'TMS', 'ERP'],
  },
  {
    term: 'TMS',
    expansion: 'Transportation Management System',
    category: 'tech',
    short: 'Software for planning, executing and settling freight movements.',
    long: 'TMS covers carrier selection, load building, route optimisation, dock scheduling, freight visibility and freight settlement. Major TMS vendors include Oracle OTM, Manhattan Active TM, Blue Yonder TMS, MercuryGate, Transporeon and Project44 (visibility-led).',
    related: ['WMS', 'YMS', 'OMS'],
  },
  {
    term: 'YMS',
    expansion: 'Yard Management System',
    category: 'tech',
    short: 'Software that tracks trailers, drivers and dock-door appointments in the warehouse yard.',
    long: 'A YMS coordinates check-in, gate moves, trailer pool and dock assignment. It often integrates closely with both WMS (for inbound receipt timing) and TMS (for shipment dispatch).',
    related: ['TMS', 'WMS'],
  },
  {
    term: 'Carton',
    category: 'tech',
    short: 'A single shipping case or container of product, smaller than a pallet.',
    long: 'Cartons (cases) are the typical receive unit from suppliers, carrying multiple eaches. They are tracked by case-level GTIN-14 or by SSCC labels for outbound shipments.',
    related: ['Pallet', 'GTIN'],
  },
  {
    term: 'Pallet',
    category: 'tech',
    short: 'A standard-sized flat platform on which goods are stacked and moved as a unit.',
    long: 'Common standards include the EUR-pallet (1200×800 mm) in Europe, the GMA pallet (48×40 in) in North America, and CHEP / LPR pooled pallets used in retail. SSCC labels are the standard logistic-unit identifier at pallet level.',
    related: ['Carton', 'SSCC'],
  },
  {
    term: 'Tote',
    category: 'tech',
    short: 'A reusable plastic container used to move and store small parts in a warehouse.',
    long: 'Totes are the typical unit-of-handling for AS/RS systems, e-commerce pick carts and miniload solutions. Sizes are typically standardised within a site (e.g. 600×400 mm Euro footprint).',
    related: ['AS/RS', 'Cluster picking'],
  },

  // ─── Roles ─────────────────────────────────────────────
  {
    term: 'WMS Functional Consultant',
    category: 'role',
    short: 'A consultant who configures the WMS to match a customer\'s warehouse processes.',
    long: 'Day-to-day work covers process discovery, configuring inbound / outbound flows, building waves, tuning allocation, slotting, and labour. Typically vendor-product specific (e.g. Manhattan, Blue Yonder, SAP EWM, D365 SCM).',
    related: ['Solution Architect', 'Implementation Lead'],
  },
  {
    term: 'Solution Architect',
    category: 'role',
    short: 'Senior role that owns the end-to-end technical design of a WMS / supply chain implementation.',
    long: 'Solution architects sit across functional, integration, infrastructure and data design. They sign off on cross-system flows, performance and extensibility decisions.',
    related: ['WMS Functional Consultant', 'Integration Engineer'],
  },
  {
    term: 'Implementation Lead',
    category: 'role',
    short: 'Project lead who runs a single warehouse go-live or workstream within a wider programme.',
    long: 'Responsible for plan, scope, resource allocation, day-to-day issue management, UAT and cut-over. Reports into the programme manager on multi-site rollouts.',
    related: ['Programme Manager', 'WMS Functional Consultant'],
  },
  {
    term: 'Programme Manager',
    category: 'role',
    short: 'Owns the overall delivery of a multi-site or multi-workstream WMS programme.',
    long: 'Accountable for the entire delivery: scope, schedule, budget, governance, risk and stakeholder management across multiple parallel workstreams.',
    related: ['Implementation Lead', 'Solution Architect'],
  },
  {
    term: 'Process Analyst',
    category: 'role',
    short: 'Maps current and future warehouse processes and translates them into WMS configuration requirements.',
    long: 'Often a customer-side role, working closely with operations supervisors. The output is a process model and configuration spec that the functional consultants implement.',
    related: ['WMS Functional Consultant', 'Product Owner'],
  },
  {
    term: 'Integration Engineer',
    category: 'role',
    short: 'Builds and maintains the technical integrations between WMS, ERP, OMS, TMS and automation.',
    long: 'Skills span EDI, REST / SOAP APIs, message brokers (Kafka, MQ), iPaaS platforms and vendor-specific integration toolkits. Critical role on any non-trivial WMS programme.',
    related: ['Solution Architect', 'EDI'],
  },
  {
    term: 'Product Owner',
    category: 'role',
    short: 'Customer-side or vendor-side role that owns a product backlog and prioritises WMS / supply chain change.',
    long: 'On long-running WMS programmes the product owner sets sprint priorities, signs off acceptance criteria and is the single point of decision on feature trade-offs.',
    related: ['Process Analyst', 'Programme Manager'],
  },

  // ─── Metrics ──────────────────────────────────────────
  {
    term: 'Pick rate',
    category: 'metric',
    short: 'Picks per labour hour. The headline productivity measure for a picking operation.',
    long: 'Pick rate varies significantly with pick method (single-line vs batch vs cluster), product profile and travel distance. Comparable rates require comparable methods.',
    related: ['Throughput', 'Cycle time'],
  },
  {
    term: 'Order accuracy',
    category: 'metric',
    short: 'The percentage of orders shipped exactly correct — right SKUs, right quantities, no extras.',
    long: 'Often measured as the inverse of mispick / overpick / underpick rates. Best-in-class enterprise sites typically run >99.9%.',
    related: ['Inventory accuracy', 'OTIF'],
  },
  {
    term: 'Cycle time',
    category: 'metric',
    short: 'Elapsed time from a defined start to a defined end of a process.',
    long: 'Used at order, wave or task level. Examples: order-to-ship cycle time, dock-to-stock cycle time, replenishment cycle time.',
    related: ['Dock-to-stock time', 'Throughput'],
  },
  {
    term: 'Dock-to-stock time',
    category: 'metric',
    short: 'Elapsed time between receiving a load at the inbound dock and the stock being putaway and available to ship.',
    long: 'A key inbound-flow KPI. Long dock-to-stock times typically signal labour, putaway-strategy or cross-dock gaps.',
    related: ['Goods receipt', 'Putaway'],
  },
  {
    term: 'Inventory accuracy',
    category: 'metric',
    short: 'How closely on-hand quantities in the WMS match what is physically present.',
    long: 'Measured by audit, cycle counting and exception reconciliation. Mature operations expect 99.5%+ at the location level. Drives shipping reliability and forecasting quality.',
    related: ['Cycle counting', 'Order accuracy'],
  },
  {
    term: 'OTIF',
    expansion: 'On-Time-In-Full',
    category: 'metric',
    short: 'Percentage of orders delivered both on time AND complete to the customer.',
    long: 'A combined service-level metric used heavily in retail and grocery supplier scorecards. OTIF penalties at major retailers (Walmart, Tesco) have made this a board-level KPI for many manufacturers.',
    related: ['Order accuracy', 'Cycle time'],
  },
  {
    term: 'DPMO',
    expansion: 'Defects Per Million Opportunities',
    category: 'metric',
    short: 'Six Sigma-style quality metric expressing defects normalised per million chances to fail.',
    long: 'In a warehouse, DPMO is often applied to pick errors, label errors or shipment errors. Lower is better; world-class is in the low double-digits.',
    related: ['Order accuracy'],
  },
  {
    term: 'Throughput',
    category: 'metric',
    short: 'The number of units (lines, orders, cases or pallets) processed per unit of time.',
    long: 'Common forms: units/hour, lines/hour, orders/day. Throughput is the headline capacity measure for a DC and is what automation business cases are usually anchored to.',
    related: ['Pick rate', 'Cycle time'],
  },

  // ─── Standards ────────────────────────────────────────
  {
    term: 'GS1',
    category: 'standard',
    short: 'The international standards body that issues UPC, EAN, GTIN, SSCC and related supply chain identifiers.',
    long: 'GS1 maintains a federated model of member organisations (GS1 US, GS1 UK, etc.). The standards cover identifiers, barcode symbologies, EDI and EPC/RFID, and underpin most retail and healthcare supply chains.',
    related: ['GTIN', 'SSCC', 'EPCIS'],
  },
  {
    term: 'EPCIS',
    expansion: 'Electronic Product Code Information Services',
    category: 'standard',
    short: 'A GS1 standard for sharing event-level supply chain data ("what, where, when, why") between trading partners.',
    long: 'EPCIS is widely used in pharmaceutical traceability (DSCSA, EU FMD) and increasingly in food and apparel. It underpins many serialisation and track-and-trace solutions.',
    related: ['GS1', 'RFID'],
  },
  {
    term: 'SSCC',
    expansion: 'Serial Shipping Container Code',
    category: 'standard',
    short: 'An 18-digit GS1 identifier for a logistic unit (typically a pallet or a case).',
    long: 'SSCCs uniquely identify a shipped logistic unit and link it to the ASN. They are commonly printed on a GS1-128 logistic label and scanned at receiving to confirm what arrived.',
    related: ['ASN', 'GS1', 'GTIN'],
  },
]
